// import type { Metadata } from "next";
// import localFont from "next/font/local"; // Local font import
// import "./globals.css";
// import Top from "@/components/Header";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// // Local font import
// const geistSans = localFont({
//   src: "/fonts/GeistMonoVF.woff", // Font ka path ab public/fonts mein hoga
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "/fonts/GeistVF.woff", // Font ka path ab public/fonts mein hoga
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Top />
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }




import { Roboto, Open_Sans } from "next/font/google"; 
import "./globals.css"; 
import Top from "@/components/Header"; 
import Navbar from "@/components/Navbar"; 
import Footer from "@/components/Footer";

// Google Fonts ko import karna
const roboto = Roboto({
  subsets: ["latin"], // Subsets for Roboto font
  weight: "400", // Roboto font weight
  variable: "--font-roboto", // CSS variable for Roboto
});

const openSans = Open_Sans({
  subsets: ["latin"], // Subsets for Open Sans font
  weight: "400", // Open Sans font weight
  variable: "--font-open-sans", // CSS variable for Open Sans
});

export const metadata = {
  title: "Your App",
  description: "Your app description",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${openSans.variable} antialiased`}>
        <Top />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}